// Mock data cho trang Admin — dùng để demo, không cần database

// Danh sách sản phẩm (có biến thể màu + size)
export const ADMIN_PRODUCTS = [
  {
    id: "p1",
    name: "Áo Blazer Linen Phom Rộng",
    category: "Áo khoác",
    price: 4500000,
    description: "Blazer linen cao cấp, form rộng thoáng mát phù hợp mùa hè.",
    image1: "/images/img_0157ad84.jpg",
    image2: "/images/img_61023194.jpg",
    // Danh sách màu sắc
    colors: [
      { hex: "#2f2f2f", name: "Xám Đen" },
      { hex: "#c8b89a", name: "Kem Cát" },
    ],
    // Danh sách size
    sizes: ["S", "M", "L", "XL"],
    // Tồn kho theo từng biến thể (color_hex + size)
    variants: [
      { color: "#2f2f2f", size: "S", stock: 3 },
      { color: "#2f2f2f", size: "M", stock: 5 },
      { color: "#2f2f2f", size: "L", stock: 4 },
      { color: "#2f2f2f", size: "XL", stock: 2 },
      { color: "#c8b89a", size: "S", stock: 2 },
      { color: "#c8b89a", size: "M", stock: 4 },
      { color: "#c8b89a", size: "L", stock: 3 },
      { color: "#c8b89a", size: "XL", stock: 1 },
    ],
  },
  {
    id: "p2",
    name: "Áo Sơ mi Form Rộng",
    category: "Áo sơ mi",
    price: 1850000,
    description: "Sơ mi form rộng unisex, chất liệu poplin mềm mỏng.",
    image1: "/images/img_7348f528.jpg",
    image2: "/images/img_6a6a622f.jpg",
    colors: [
      { hex: "#1a1c1c", name: "Đen Nhám" },
      { hex: "#f5f0e8", name: "Trắng Kem" },
      { hex: "#4a3728", name: "Nâu Đất" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    variants: [
      { color: "#1a1c1c", size: "S", stock: 5 },
      { color: "#1a1c1c", size: "M", stock: 8 },
      { color: "#1a1c1c", size: "L", stock: 6 },
      { color: "#1a1c1c", size: "XL", stock: 4 },
      { color: "#1a1c1c", size: "XXL", stock: 2 },
      { color: "#f5f0e8", size: "S", stock: 3 },
      { color: "#f5f0e8", size: "M", stock: 5 },
      { color: "#f5f0e8", size: "L", stock: 4 },
      { color: "#f5f0e8", size: "XL", stock: 2 },
      { color: "#f5f0e8", size: "XXL", stock: 1 },
      { color: "#4a3728", size: "S", stock: 2 },
      { color: "#4a3728", size: "M", stock: 3 },
      { color: "#4a3728", size: "L", stock: 2 },
      { color: "#4a3728", size: "XL", stock: 1 },
      { color: "#4a3728", size: "XXL", stock: 0 },
    ],
  },
  {
    id: "p3",
    name: "Quần Khaki Chino",
    category: "Quần",
    price: 2200000,
    description: "Quần khaki chino 5 túi, chất liệu cotton pha elastane.",
    image1: "/images/img_87c1233f.jpg",
    image2: "/images/img_0e5ef52b.jpg",
    colors: [
      { hex: "#c8b89a", name: "Be Đất" },
      { hex: "#3d3d3d", name: "Xám Than" },
    ],
    sizes: ["28", "30", "32", "34", "36"],
    variants: [
      { color: "#c8b89a", size: "28", stock: 4 },
      { color: "#c8b89a", size: "30", stock: 6 },
      { color: "#c8b89a", size: "32", stock: 5 },
      { color: "#c8b89a", size: "34", stock: 3 },
      { color: "#c8b89a", size: "36", stock: 1 },
      { color: "#3d3d3d", size: "28", stock: 2 },
      { color: "#3d3d3d", size: "30", stock: 4 },
      { color: "#3d3d3d", size: "32", stock: 3 },
      { color: "#3d3d3d", size: "34", stock: 2 },
      { color: "#3d3d3d", size: "36", stock: 0 },
    ],
  },
  {
    id: "p4",
    name: "Giày da Loafer",
    category: "Giày",
    price: 3900000,
    description: "Loafer da bò thật, đế cao su, thích hợp đi công sở.",
    image1: "/images/img_58b90532.jpg",
    image2: "/images/img_74203803.jpg",
    colors: [
      { hex: "#1a1c1c", name: "Đen" },
      { hex: "#4a3728", name: "Nâu" },
    ],
    sizes: ["39", "40", "41", "42", "43", "44"],
    variants: [
      { color: "#1a1c1c", size: "39", stock: 2 },
      { color: "#1a1c1c", size: "40", stock: 3 },
      { color: "#1a1c1c", size: "41", stock: 2 },
      { color: "#1a1c1c", size: "42", stock: 1 },
      { color: "#1a1c1c", size: "43", stock: 1 },
      { color: "#1a1c1c", size: "44", stock: 0 },
      { color: "#4a3728", size: "39", stock: 1 },
      { color: "#4a3728", size: "40", stock: 2 },
      { color: "#4a3728", size: "41", stock: 2 },
      { color: "#4a3728", size: "42", stock: 1 },
      { color: "#4a3728", size: "43", stock: 0 },
      { color: "#4a3728", size: "44", stock: 0 },
    ],
  },
  {
    id: "p5",
    name: "Áo len Cổ tròn Anthracite",
    category: "Áo len",
    price: 2800000,
    description: "Áo len cổ tròn dệt dày, giữ ấm tốt cho mùa đông.",
    image1: "/images/img_678c6f7e.jpg",
    image2: "/images/img_678c6f7e.jpg",
    colors: [
      { hex: "#3d3d3d", name: "Anthracite" },
      { hex: "#1a1c1c", name: "Đen" },
      { hex: "#8b6f5e", name: "Nâu Mocha" },
    ],
    sizes: ["S", "M", "L", "XL"],
    variants: [
      { color: "#3d3d3d", size: "S", stock: 4 },
      { color: "#3d3d3d", size: "M", stock: 5 },
      { color: "#3d3d3d", size: "L", stock: 3 },
      { color: "#3d3d3d", size: "XL", stock: 2 },
      { color: "#1a1c1c", size: "S", stock: 3 },
      { color: "#1a1c1c", size: "M", stock: 4 },
      { color: "#1a1c1c", size: "L", stock: 2 },
      { color: "#1a1c1c", size: "XL", stock: 1 },
      { color: "#8b6f5e", size: "S", stock: 2 },
      { color: "#8b6f5e", size: "M", stock: 3 },
      { color: "#8b6f5e", size: "L", stock: 1 },
      { color: "#8b6f5e", size: "XL", stock: 0 },
    ],
  },
  {
    id: "p6",
    name: "Áo khoác dạ dáng dài",
    category: "Áo khoác",
    price: 12500000,
    description: "Áo khoác dạ cao cấp dáng dài, lót trong ấm, form cổ điển.",
    image1: "/images/img_def6a453.jpg",
    image2: "/images/img_def6a453.jpg",
    colors: [
      { hex: "#1a1c1c", name: "Đen" },
      { hex: "#2f2f2f", name: "Xám Đen" },
    ],
    sizes: ["M", "L", "XL"],
    variants: [
      { color: "#1a1c1c", size: "M", stock: 2 },
      { color: "#1a1c1c", size: "L", stock: 2 },
      { color: "#1a1c1c", size: "XL", stock: 1 },
      { color: "#2f2f2f", size: "M", stock: 1 },
      { color: "#2f2f2f", size: "L", stock: 1 },
      { color: "#2f2f2f", size: "XL", stock: 0 },
    ],
  },
];

// Danh sách đơn hàng
export const ADMIN_ORDERS = [
  {
    id: "NM-49201",
    date: "24/10/2024",
    customer: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "+84 987 654 321",
    address: "Khu vực Sảnh A, Tòa ICT, Quận Cầu Giấy, Hà Nội",
    payment: "COD",
    status: "Chờ xác nhận",
    total: 12400000,
    items: [
      { name: "Áo khoác dạ dáng dài", size: "M", qty: 1, price: 12400000 },
    ],
  },
  {
    id: "NM-48592",
    date: "12/09/2024",
    customer: "Trần Minh B",
    email: "tranminhb@example.com",
    phone: "+84 912 345 678",
    address: "123 Nguyễn Trãi, Quận 1, TP.HCM",
    payment: "Sepay",
    status: "Đã giao",
    total: 4500000,
    items: [
      { name: "Áo Blazer Linen", size: "L", qty: 1, price: 4500000 },
    ],
  },
  {
    id: "NM-47110",
    date: "05/08/2024",
    customer: "Lê Hoàng C",
    email: "lehoangg@example.com",
    phone: "+84 976 543 210",
    address: "456 Lê Lợi, Quận Hoàn Kiếm, Hà Nội",
    payment: "COD",
    status: "Đã giao",
    total: 28900000,
    items: [
      { name: "Áo khoác dài Obsidian", size: "XL", qty: 1, price: 21200000 },
      { name: "Quần Khaki Chino", size: "32", qty: 1, price: 2200000 },
      { name: "Giày da Loafer", size: "42", qty: 1, price: 5500000 },
    ],
  },
  {
    id: "NM-46029",
    date: "18/06/2024",
    customer: "Phạm Đức D",
    email: "phamduc@example.com",
    phone: "+84 901 234 567",
    address: "789 Đinh Tiên Hoàng, Quận Bình Thạnh, TP.HCM",
    payment: "COD",
    status: "Đã hủy",
    total: 1250000,
    items: [
      { name: "Áo Sơ mi Form Rộng", size: "S", qty: 1, price: 1250000 },
    ],
  },
  {
    id: "NM-45318",
    date: "02/05/2024",
    customer: "Hoàng Quân E",
    email: "hoangquan@example.com",
    phone: "+84 965 432 109",
    address: "321 Trần Hưng Đạo, Quận 5, TP.HCM",
    payment: "Sepay",
    status: "Đã giao",
    total: 6700000,
    items: [
      { name: "Áo len Anthracite", size: "M", qty: 1, price: 2800000 },
      { name: "Quần Khaki Chino", size: "30", qty: 1, price: 2200000 },
      { name: "Áo Sơ mi Form Rộng", size: "M", qty: 1, price: 1700000 },
    ],
  },
];

// Danh sách người dùng
export const ADMIN_USERS = [
  {
    id: "u1",
    fullName: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "+84 987 654 321",
    tier: "Hạng Đen",
    points: 1250,
    joined: "Tháng 10, 2023",
    city: "Hà Nội",
    orderCount: 3,
    totalSpent: 45700000,
  },
  {
    id: "u2",
    fullName: "Trần Minh B",
    email: "tranminhb@example.com",
    phone: "+84 912 345 678",
    tier: "Hạng Bạc",
    points: 450,
    joined: "Tháng 03, 2024",
    city: "TP.HCM",
    orderCount: 1,
    totalSpent: 4500000,
  },
  {
    id: "u3",
    fullName: "Lê Hoàng C",
    email: "lehoangg@example.com",
    phone: "+84 976 543 210",
    tier: "Hạng Vàng",
    points: 890,
    joined: "Tháng 01, 2024",
    city: "Hà Nội",
    orderCount: 2,
    totalSpent: 35600000,
  },
  {
    id: "u4",
    fullName: "Phạm Đức D",
    email: "phamduc@example.com",
    phone: "+84 901 234 567",
    tier: "Hạng Đồng",
    points: 50,
    joined: "Tháng 06, 2024",
    city: "TP.HCM",
    orderCount: 1,
    totalSpent: 1250000,
  },
  {
    id: "u5",
    fullName: "Hoàng Quân E",
    email: "hoangquan@example.com",
    phone: "+84 965 432 109",
    tier: "Hạng Bạc",
    points: 670,
    joined: "Tháng 02, 2024",
    city: "TP.HCM",
    orderCount: 1,
    totalSpent: 6700000,
  },
];

// Danh mục sản phẩm
export const ADMIN_CATEGORIES = [
  { id: "cat1", name: "Áo khoác", slug: "ao-khoac", productCount: 2, description: "Áo khoác nam các loại" },
  { id: "cat2", name: "Áo sơ mi", slug: "ao-so-mi", productCount: 1, description: "Áo sơ mi nam form rộng và slim" },
  { id: "cat3", name: "Áo len", slug: "ao-len", productCount: 1, description: "Áo len, áo sweater nam" },
  { id: "cat4", name: "Quần", slug: "quan", productCount: 1, description: "Quần khaki, chino, jeans" },
  { id: "cat5", name: "Giày", slug: "giay", productCount: 1, description: "Giày da, sneaker, loafer" },
  { id: "cat6", name: "Phụ kiện", slug: "phu-kien", productCount: 0, description: "Thắt lưng, ví, kính mắt" },
];
